# Generated by Django 3.0.3 on 2020-04-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0002_auto_20200417_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='title',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pwd',
        ),
    ]
