# Generated by Django 3.0.3 on 2020-04-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0004_auto_20200417_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
