# Generated by Django 3.0.3 on 2020-04-17 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BloggerModel', '0005_auto_20200417_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='user<django.db.models.fields.AutoField>', max_length=30)),
                ('pwd', models.CharField(default='123456', max_length=15)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('email', models.CharField(default=None, max_length=30, unique=True)),
                ('introduction', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=50)),
                ('content', models.CharField(default=None, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BloggerModel.Users')),
            ],
        ),
    ]
