# Generated by Django 3.0.3 on 2020-04-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0006_blogs_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BloggerModel.Blogs')),
                ('tagid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BloggerModel.Tags')),
            ],
        ),
    ]
