# Generated by Django 3.0.3 on 2020-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0008_comments_dislikeblogs_favoritetags_likeblogs_news_userinteractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='occupation',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
