# Generated by Django 3.0.3 on 2020-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0009_users_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='occupation',
            field=models.CharField(default='Not Known', max_length=20),
        ),
    ]
