# Generated by Django 3.0.3 on 2020-04-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0010_auto_20200426_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
