# Generated by Django 3.0.3 on 2020-04-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0011_blogs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
