# Generated by Django 3.0.3 on 2020-05-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0014_auto_20200502_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='tagid',
        ),
    ]
