# Generated by Django 3.0.3 on 2020-05-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0016_auto_20200502_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='uesr_id',
            new_name='user_id',
        ),
    ]
