# Generated by Django 3.0.3 on 2020-05-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerModel', '0017_auto_20200503_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
